# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import warnings

import grpc

from protos import task_pb2 as protos_dot_task__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in protos/task_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class TaskServiceStub(object):
    """TaskService 定义了任务执行与管理的 RPC 接口。"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CollectBinance = channel.unary_unary(
            "/task.v1.TaskService/CollectBinance",
            request_serializer=protos_dot_task__pb2.CollectBinanceRequest.SerializeToString,
            response_deserializer=protos_dot_task__pb2.TaskResponse.FromString,
            _registered_method=True,
        )
        self.CollectBinanceByDate = channel.unary_unary(
            "/task.v1.TaskService/CollectBinanceByDate",
            request_serializer=protos_dot_task__pb2.CollectBinaceByDateRequest.SerializeToString,
            response_deserializer=protos_dot_task__pb2.TaskResponse.FromString,
            _registered_method=True,
        )
        self.CollectUniswap = channel.unary_unary(
            "/task.v1.TaskService/CollectUniswap",
            request_serializer=protos_dot_task__pb2.CollectUniswapRequest.SerializeToString,
            response_deserializer=protos_dot_task__pb2.TaskResponse.FromString,
            _registered_method=True,
        )
        self.ProcessPrices = channel.unary_unary(
            "/task.v1.TaskService/ProcessPrices",
            request_serializer=protos_dot_task__pb2.ProcessPricesRequest.SerializeToString,
            response_deserializer=protos_dot_task__pb2.TaskResponse.FromString,
            _registered_method=True,
        )
        self.Analyse = channel.unary_unary(
            "/task.v1.TaskService/Analyse",
            request_serializer=protos_dot_task__pb2.AnalyseRequest.SerializeToString,
            response_deserializer=protos_dot_task__pb2.TaskResponse.FromString,
            _registered_method=True,
        )


class TaskServiceServicer(object):
    """TaskService 定义了任务执行与管理的 RPC 接口。"""

    def CollectBinance(self, request, context):
        """收集币安数据"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CollectBinanceByDate(self, request, context):
        """按日期收集币安数据"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CollectUniswap(self, request, context):
        """收集Uniswap数据"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ProcessPrices(self, request, context):
        """处理价格数据"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Analyse(self, request, context):
        """分析数据"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_TaskServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CollectBinance": grpc.unary_unary_rpc_method_handler(
            servicer.CollectBinance,
            request_deserializer=protos_dot_task__pb2.CollectBinanceRequest.FromString,
            response_serializer=protos_dot_task__pb2.TaskResponse.SerializeToString,
        ),
        "CollectBinanceByDate": grpc.unary_unary_rpc_method_handler(
            servicer.CollectBinanceByDate,
            request_deserializer=protos_dot_task__pb2.CollectBinaceByDateRequest.FromString,
            response_serializer=protos_dot_task__pb2.TaskResponse.SerializeToString,
        ),
        "CollectUniswap": grpc.unary_unary_rpc_method_handler(
            servicer.CollectUniswap,
            request_deserializer=protos_dot_task__pb2.CollectUniswapRequest.FromString,
            response_serializer=protos_dot_task__pb2.TaskResponse.SerializeToString,
        ),
        "ProcessPrices": grpc.unary_unary_rpc_method_handler(
            servicer.ProcessPrices,
            request_deserializer=protos_dot_task__pb2.ProcessPricesRequest.FromString,
            response_serializer=protos_dot_task__pb2.TaskResponse.SerializeToString,
        ),
        "Analyse": grpc.unary_unary_rpc_method_handler(
            servicer.Analyse,
            request_deserializer=protos_dot_task__pb2.AnalyseRequest.FromString,
            response_serializer=protos_dot_task__pb2.TaskResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "task.v1.TaskService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("task.v1.TaskService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class TaskService(object):
    """TaskService 定义了任务执行与管理的 RPC 接口。"""

    @staticmethod
    def CollectBinance(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/task.v1.TaskService/CollectBinance",
            protos_dot_task__pb2.CollectBinanceRequest.SerializeToString,
            protos_dot_task__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CollectBinanceByDate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/task.v1.TaskService/CollectBinanceByDate",
            protos_dot_task__pb2.CollectBinaceByDateRequest.SerializeToString,
            protos_dot_task__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CollectUniswap(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/task.v1.TaskService/CollectUniswap",
            protos_dot_task__pb2.CollectUniswapRequest.SerializeToString,
            protos_dot_task__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ProcessPrices(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/task.v1.TaskService/ProcessPrices",
            protos_dot_task__pb2.ProcessPricesRequest.SerializeToString,
            protos_dot_task__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Analyse(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/task.v1.TaskService/Analyse",
            protos_dot_task__pb2.AnalyseRequest.SerializeToString,
            protos_dot_task__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
