// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.3
// source: task.proto

package taskpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TaskStatus 定义任务的可能状态。
type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_RUNNING  TaskStatus = 0 // 任务正在执行中
	TaskStatus_TASK_STATUS_SUCCESS  TaskStatus = 1 // 任务成功完成
	TaskStatus_TASK_STATUS_FAILED   TaskStatus = 2 // 任务执行失败
	TaskStatus_TASK_STATUS_CANCELED TaskStatus = 3 // 任务被取消
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_RUNNING",
		1: "TASK_STATUS_SUCCESS",
		2: "TASK_STATUS_FAILED",
		3: "TASK_STATUS_CANCELED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_RUNNING":  0,
		"TASK_STATUS_SUCCESS":  1,
		"TASK_STATUS_FAILED":   2,
		"TASK_STATUS_CANCELED": 3,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_task_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_task_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{0}
}

type CollectBinanceRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TaskId           string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                                // 任务的唯一标识符
	ImportPercentage int32                  `protobuf:"varint,2,opt,name=import_percentage,json=importPercentage,proto3" json:"import_percentage,omitempty"` // 导入百分比
	ChunkSize        int32                  `protobuf:"varint,3,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`                      // 分块大小
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CollectBinanceRequest) Reset() {
	*x = CollectBinanceRequest{}
	mi := &file_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectBinanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectBinanceRequest) ProtoMessage() {}

func (x *CollectBinanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectBinanceRequest.ProtoReflect.Descriptor instead.
func (*CollectBinanceRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{0}
}

func (x *CollectBinanceRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CollectBinanceRequest) GetImportPercentage() int32 {
	if x != nil {
		return x.ImportPercentage
	}
	return 0
}

func (x *CollectBinanceRequest) GetChunkSize() int32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

type CollectUniswapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                // 任务的唯一标识符
	PoolAddress   string                 `protobuf:"bytes,2,opt,name=pool_address,json=poolAddress,proto3" json:"pool_address,omitempty"` // 池地址
	StartTs       int32                  `protobuf:"varint,3,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`            // 起始时间
	EndTs         int32                  `protobuf:"varint,4,opt,name=end_ts,json=endTs,proto3" json:"end_ts,omitempty"`                  // 终止时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectUniswapRequest) Reset() {
	*x = CollectUniswapRequest{}
	mi := &file_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectUniswapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectUniswapRequest) ProtoMessage() {}

func (x *CollectUniswapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectUniswapRequest.ProtoReflect.Descriptor instead.
func (*CollectUniswapRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{1}
}

func (x *CollectUniswapRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CollectUniswapRequest) GetPoolAddress() string {
	if x != nil {
		return x.PoolAddress
	}
	return ""
}

func (x *CollectUniswapRequest) GetStartTs() int32 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *CollectUniswapRequest) GetEndTs() int32 {
	if x != nil {
		return x.EndTs
	}
	return 0
}

type ProcessPricesRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TaskId              string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                                                                                          // 任务的唯一标识符
	StartDate           int32                  `protobuf:"varint,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`                                                                                // 起始时间
	EndDate             int32                  `protobuf:"varint,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`                                                                                      // 终止时间
	AggregationInterval string                 `protobuf:"bytes,4,opt,name=aggregation_interval,json=aggregationInterval,proto3" json:"aggregation_interval,omitempty"`                                                   // 聚合间隔
	Overwrite           bool                   `protobuf:"varint,5,opt,name=overwrite,proto3" json:"overwrite,omitempty"`                                                                                                 // 是否覆盖
	DbOverrides         map[string]string      `protobuf:"bytes,6,rep,name=db_overrides,json=dbOverrides,proto3" json:"db_overrides,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 策略参数
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProcessPricesRequest) Reset() {
	*x = ProcessPricesRequest{}
	mi := &file_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPricesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPricesRequest) ProtoMessage() {}

func (x *ProcessPricesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPricesRequest.ProtoReflect.Descriptor instead.
func (*ProcessPricesRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessPricesRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ProcessPricesRequest) GetStartDate() int32 {
	if x != nil {
		return x.StartDate
	}
	return 0
}

func (x *ProcessPricesRequest) GetEndDate() int32 {
	if x != nil {
		return x.EndDate
	}
	return 0
}

func (x *ProcessPricesRequest) GetAggregationInterval() string {
	if x != nil {
		return x.AggregationInterval
	}
	return ""
}

func (x *ProcessPricesRequest) GetOverwrite() bool {
	if x != nil {
		return x.Overwrite
	}
	return false
}

func (x *ProcessPricesRequest) GetDbOverrides() map[string]string {
	if x != nil {
		return x.DbOverrides
	}
	return nil
}

type AnalyseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                   // 任务的唯一标识符
	BatchId       int32                  `protobuf:"varint,2,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`               // 批次ID
	Overwrite     bool                   `protobuf:"varint,3,opt,name=overwrite,proto3" json:"overwrite,omitempty"`                          // 是否覆盖
	StrategyJson  string                 `protobuf:"bytes,4,opt,name=strategy_json,json=strategyJson,proto3" json:"strategy_json,omitempty"` // 策略参数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyseRequest) Reset() {
	*x = AnalyseRequest{}
	mi := &file_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyseRequest) ProtoMessage() {}

func (x *AnalyseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyseRequest.ProtoReflect.Descriptor instead.
func (*AnalyseRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{3}
}

func (x *AnalyseRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AnalyseRequest) GetBatchId() int32 {
	if x != nil {
		return x.BatchId
	}
	return 0
}

func (x *AnalyseRequest) GetOverwrite() bool {
	if x != nil {
		return x.Overwrite
	}
	return false
}

func (x *AnalyseRequest) GetStrategyJson() string {
	if x != nil {
		return x.StrategyJson
	}
	return ""
}

type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`            // 任务的唯一标识符
	Status        TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=task.v1.TaskStatus" json:"status,omitempty"` // 任务的最终状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{4}
}

func (x *TaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResponse) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_RUNNING
}

var File_task_proto protoreflect.FileDescriptor

const file_task_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"task.proto\x12\atask.v1\"|\n" +
	"\x15CollectBinanceRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12+\n" +
	"\x11import_percentage\x18\x02 \x01(\x05R\x10importPercentage\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x03 \x01(\x05R\tchunkSize\"\x85\x01\n" +
	"\x15CollectUniswapRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12!\n" +
	"\fpool_address\x18\x02 \x01(\tR\vpoolAddress\x12\x19\n" +
	"\bstart_ts\x18\x03 \x01(\x05R\astartTs\x12\x15\n" +
	"\x06end_ts\x18\x04 \x01(\x05R\x05endTs\"\xcd\x02\n" +
	"\x14ProcessPricesRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\x05R\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\x05R\aendDate\x121\n" +
	"\x14aggregation_interval\x18\x04 \x01(\tR\x13aggregationInterval\x12\x1c\n" +
	"\toverwrite\x18\x05 \x01(\bR\toverwrite\x12Q\n" +
	"\fdb_overrides\x18\x06 \x03(\v2..task.v1.ProcessPricesRequest.DbOverridesEntryR\vdbOverrides\x1a>\n" +
	"\x10DbOverridesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x01\n" +
	"\x0eAnalyseRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x19\n" +
	"\bbatch_id\x18\x02 \x01(\x05R\abatchId\x12\x1c\n" +
	"\toverwrite\x18\x03 \x01(\bR\toverwrite\x12#\n" +
	"\rstrategy_json\x18\x04 \x01(\tR\fstrategyJson\"T\n" +
	"\fTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12+\n" +
	"\x06status\x18\x02 \x01(\x0e2\x13.task.v1.TaskStatusR\x06status*p\n" +
	"\n" +
	"TaskStatus\x12\x17\n" +
	"\x13TASK_STATUS_RUNNING\x10\x00\x12\x17\n" +
	"\x13TASK_STATUS_SUCCESS\x10\x01\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\x02\x12\x18\n" +
	"\x14TASK_STATUS_CANCELED\x10\x032\xa1\x02\n" +
	"\vTaskService\x12G\n" +
	"\x0eCollectBinance\x12\x1e.task.v1.CollectBinanceRequest\x1a\x15.task.v1.TaskResponse\x12G\n" +
	"\x0eCollectUniswap\x12\x1e.task.v1.CollectUniswapRequest\x1a\x15.task.v1.TaskResponse\x12E\n" +
	"\rProcessPrices\x12\x1d.task.v1.ProcessPricesRequest\x1a\x15.task.v1.TaskResponse\x129\n" +
	"\aAnalyse\x12\x17.task.v1.AnalyseRequest\x1a\x15.task.v1.TaskResponseB\x1bZ\x19backend/pkg/taskpb;taskpbb\x06proto3"

var (
	file_task_proto_rawDescOnce sync.Once
	file_task_proto_rawDescData []byte
)

func file_task_proto_rawDescGZIP() []byte {
	file_task_proto_rawDescOnce.Do(func() {
		file_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_proto_rawDesc), len(file_task_proto_rawDesc)))
	})
	return file_task_proto_rawDescData
}

var file_task_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_task_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_task_proto_goTypes = []any{
	(TaskStatus)(0),               // 0: task.v1.TaskStatus
	(*CollectBinanceRequest)(nil), // 1: task.v1.CollectBinanceRequest
	(*CollectUniswapRequest)(nil), // 2: task.v1.CollectUniswapRequest
	(*ProcessPricesRequest)(nil),  // 3: task.v1.ProcessPricesRequest
	(*AnalyseRequest)(nil),        // 4: task.v1.AnalyseRequest
	(*TaskResponse)(nil),          // 5: task.v1.TaskResponse
	nil,                           // 6: task.v1.ProcessPricesRequest.DbOverridesEntry
}
var file_task_proto_depIdxs = []int32{
	6, // 0: task.v1.ProcessPricesRequest.db_overrides:type_name -> task.v1.ProcessPricesRequest.DbOverridesEntry
	0, // 1: task.v1.TaskResponse.status:type_name -> task.v1.TaskStatus
	1, // 2: task.v1.TaskService.CollectBinance:input_type -> task.v1.CollectBinanceRequest
	2, // 3: task.v1.TaskService.CollectUniswap:input_type -> task.v1.CollectUniswapRequest
	3, // 4: task.v1.TaskService.ProcessPrices:input_type -> task.v1.ProcessPricesRequest
	4, // 5: task.v1.TaskService.Analyse:input_type -> task.v1.AnalyseRequest
	5, // 6: task.v1.TaskService.CollectBinance:output_type -> task.v1.TaskResponse
	5, // 7: task.v1.TaskService.CollectUniswap:output_type -> task.v1.TaskResponse
	5, // 8: task.v1.TaskService.ProcessPrices:output_type -> task.v1.TaskResponse
	5, // 9: task.v1.TaskService.Analyse:output_type -> task.v1.TaskResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_task_proto_init() }
func file_task_proto_init() {
	if File_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_proto_rawDesc), len(file_task_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_task_proto_goTypes,
		DependencyIndexes: file_task_proto_depIdxs,
		EnumInfos:         file_task_proto_enumTypes,
		MessageInfos:      file_task_proto_msgTypes,
	}.Build()
	File_task_proto = out.File
	file_task_proto_goTypes = nil
	file_task_proto_depIdxs = nil
}
