// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v4.25.3
// source: task.proto

package taskpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	TaskService_CollectBinance_FullMethodName       = "/task.v1.TaskService/CollectBinance"
	TaskService_CollectBinanceByDate_FullMethodName = "/task.v1.TaskService/CollectBinanceByDate"
	TaskService_CollectUniswap_FullMethodName       = "/task.v1.TaskService/CollectUniswap"
	TaskService_ProcessPrices_FullMethodName        = "/task.v1.TaskService/ProcessPrices"
	TaskService_Analyse_FullMethodName              = "/task.v1.TaskService/Analyse"
)

// TaskServiceClient is the client API for TaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TaskService 定义了任务执行与管理的 RPC 接口。
type TaskServiceClient interface {
	// 收集币安数据
	CollectBinance(ctx context.Context, in *CollectBinanceRequest, opts ...grpc.CallOption) (*TaskResponse, error)
	// 按日期收集币安数据
	CollectBinanceByDate(ctx context.Context, in *CollectBinanceByDateRequest, opts ...grpc.CallOption) (*TaskResponse, error)
	// 收集Uniswap数据
	CollectUniswap(ctx context.Context, in *CollectUniswapRequest, opts ...grpc.CallOption) (*TaskResponse, error)
	// 处理价格数据
	ProcessPrices(ctx context.Context, in *ProcessPricesRequest, opts ...grpc.CallOption) (*TaskResponse, error)
	// 分析数据
	Analyse(ctx context.Context, in *AnalyseRequest, opts ...grpc.CallOption) (*TaskResponse, error)
}

type taskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskServiceClient(cc grpc.ClientConnInterface) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) CollectBinance(ctx context.Context, in *CollectBinanceRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, TaskService_CollectBinance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) CollectBinanceByDate(ctx context.Context, in *CollectBinanceByDateRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, TaskService_CollectBinanceByDate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) CollectUniswap(ctx context.Context, in *CollectUniswapRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, TaskService_CollectUniswap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) ProcessPrices(ctx context.Context, in *ProcessPricesRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, TaskService_ProcessPrices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) Analyse(ctx context.Context, in *AnalyseRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, TaskService_Analyse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskServiceServer is the server API for TaskService service.
// All implementations must embed UnimplementedTaskServiceServer
// for forward compatibility
//
// TaskService 定义了任务执行与管理的 RPC 接口。
type TaskServiceServer interface {
	// 收集币安数据
	CollectBinance(context.Context, *CollectBinanceRequest) (*TaskResponse, error)
	// 按日期收集币安数据
	CollectBinanceByDate(context.Context, *CollectBinanceByDateRequest) (*TaskResponse, error)
	// 收集Uniswap数据
	CollectUniswap(context.Context, *CollectUniswapRequest) (*TaskResponse, error)
	// 处理价格数据
	ProcessPrices(context.Context, *ProcessPricesRequest) (*TaskResponse, error)
	// 分析数据
	Analyse(context.Context, *AnalyseRequest) (*TaskResponse, error)
	mustEmbedUnimplementedTaskServiceServer()
}

// UnimplementedTaskServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTaskServiceServer struct {
}

func (UnimplementedTaskServiceServer) CollectBinance(context.Context, *CollectBinanceRequest) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CollectBinance not implemented")
}
func (UnimplementedTaskServiceServer) CollectBinanceByDate(context.Context, *CollectBinanceByDateRequest) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CollectBinanceByDate not implemented")
}
func (UnimplementedTaskServiceServer) CollectUniswap(context.Context, *CollectUniswapRequest) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CollectUniswap not implemented")
}
func (UnimplementedTaskServiceServer) ProcessPrices(context.Context, *ProcessPricesRequest) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessPrices not implemented")
}
func (UnimplementedTaskServiceServer) Analyse(context.Context, *AnalyseRequest) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Analyse not implemented")
}
func (UnimplementedTaskServiceServer) mustEmbedUnimplementedTaskServiceServer() {}

// UnsafeTaskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskServiceServer will
// result in compilation errors.
type UnsafeTaskServiceServer interface {
	mustEmbedUnimplementedTaskServiceServer()
}

func RegisterTaskServiceServer(s grpc.ServiceRegistrar, srv TaskServiceServer) {
	s.RegisterService(&TaskService_ServiceDesc, srv)
}

func _TaskService_CollectBinance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectBinanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).CollectBinance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_CollectBinance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).CollectBinance(ctx, req.(*CollectBinanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_CollectBinanceByDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectBinanceByDateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).CollectBinanceByDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_CollectBinanceByDate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).CollectBinanceByDate(ctx, req.(*CollectBinanceByDateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_CollectUniswap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectUniswapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).CollectUniswap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_CollectUniswap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).CollectUniswap(ctx, req.(*CollectUniswapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_ProcessPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessPricesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).ProcessPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_ProcessPrices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).ProcessPrices(ctx, req.(*ProcessPricesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_Analyse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).Analyse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_Analyse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).Analyse(ctx, req.(*AnalyseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskService_ServiceDesc is the grpc.ServiceDesc for TaskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "task.v1.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CollectBinance",
			Handler:    _TaskService_CollectBinance_Handler,
		},
		{
			MethodName: "CollectBinanceByDate",
			Handler:    _TaskService_CollectBinanceByDate_Handler,
		},
		{
			MethodName: "CollectUniswap",
			Handler:    _TaskService_CollectUniswap_Handler,
		},
		{
			MethodName: "ProcessPrices",
			Handler:    _TaskService_ProcessPrices_Handler,
		},
		{
			MethodName: "Analyse",
			Handler:    _TaskService_Analyse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "task.proto",
}
