// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/batches": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Batch"
                ],
                "summary": "批次列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Batch"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Batch"
                ],
                "summary": "创建批次",
                "parameters": [
                    {
                        "description": "批次信息",
                        "name": "batch",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.batchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Batch"
                        }
                    }
                }
            }
        },
        "/batches/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Batch"
                ],
                "summary": "批次详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "批次 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Batch"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Batch"
                ],
                "summary": "更新批次",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "批次 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "批次信息",
                        "name": "batch",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.batchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Batch"
                        }
                    }
                }
            }
        },
        "/opportunities": {
            "get": {
                "description": "(SRS FR-5.3) 获取套利机会列表，支持分页和排序",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Opportunities"
                ],
                "summary": "获取套利机会列表 (UC-02)",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "example": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "example": 10,
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "profit_usdt",
                        "example": "profit_usdt",
                        "description": "排序字段 (snake_case)",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "default": "desc",
                        "example": "desc",
                        "description": "排序顺序 (asc/desc)",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应 (符合 API 规范 3.1.B)",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessOpportunitiesResponse"
                        }
                    },
                    "400": {
                        "description": "参数错误 (Code: 40001, 40002)",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误 (Code: 50001)",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/price-comparison": {
            "get": {
                "description": "(SRS FR-5.2) 获取用于 ECharts 渲染的聚合价格数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Visualization"
                ],
                "summary": "获取价格对比数据 (UC-01)",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 1756694400000,
                        "description": "开始时间 (13位毫秒时间戳)",
                        "name": "startTime",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "example": 1756780799000,
                        "description": "结束时间 (13位毫秒时间戳)",
                        "name": "endTime",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应 (符合 API 规范 3.1.A)",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessPriceResponse"
                        }
                    },
                    "400": {
                        "description": "参数错误 (Code: 40001)",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误 (Code: 50001)",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/reports": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Report"
                ],
                "summary": "报告列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "批次 ID",
                        "name": "batch_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Report"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Report"
                ],
                "summary": "记录报告生成结果",
                "parameters": [
                    {
                        "description": "报告参数",
                        "name": "report",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.reportRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Report"
                        }
                    }
                }
            }
        },
        "/tasks": {
            "get": {
                "description": "查询任务列表，可分页",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "任务列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ListTasksResponse"
                        }
                    }
                }
            }
        },
        "/tasks/{task_id}": {
            "get": {
                "description": "根据 task_id 查询单个任务",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "任务详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务 ID",
                        "name": "task_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.TaskDetailResponse"
                        }
                    }
                }
            }
        },
        "/tasks/{task_id}/logs": {
            "get": {
                "description": "查询某个任务的日志",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "任务日志",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务 ID",
                        "name": "task_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "每页条数",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "偏移量",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.TaskLogResponse"
                        }
                    }
                }
            }
        },
        "/templates": {
            "get": {
                "description": "查询所有任务模板",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Template"
                ],
                "summary": "模板列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ParamTemplate"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Template"
                ],
                "summary": "创建模板",
                "parameters": [
                    {
                        "description": "模板信息",
                        "name": "template",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.templateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ParamTemplate"
                        }
                    }
                }
            }
        },
        "/templates/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Template"
                ],
                "summary": "更新模板",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "模板 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "模板信息",
                        "name": "template",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.templateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ParamTemplate"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Template"
                ],
                "summary": "删除模板",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "模板 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 40001
                },
                "message": {
                    "type": "string",
                    "example": "请求参数无效"
                }
            }
        },
        "api.ListTasksResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.TaskItem"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/api.TaskPagination"
                }
            }
        },
        "api.OpportunitiesResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ArbitrageOpportunity"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/api.PaginationData"
                }
            }
        },
        "api.PaginationData": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer",
                    "example": 10
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "total": {
                    "type": "integer",
                    "example": 150
                }
            }
        },
        "api.PriceComparisonResponse": {
            "type": "object",
            "properties": {
                "binance": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {}
                    }
                },
                "uniswap": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {}
                    }
                }
            }
        },
        "api.SuccessOpportunitiesResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 0
                },
                "data": {
                    "$ref": "#/definitions/api.OpportunitiesResponse"
                },
                "message": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "api.SuccessPriceResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 0
                },
                "data": {
                    "$ref": "#/definitions/api.PriceComparisonResponse"
                },
                "message": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "api.TaskDetailResponse": {
            "type": "object",
            "properties": {
                "config": {
                    "type": "object",
                    "additionalProperties": true
                },
                "duration_secs": {
                    "type": "integer"
                },
                "finished_at": {
                    "type": "string"
                },
                "log_summary": {
                    "type": "string"
                },
                "queued_at": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "task_id": {
                    "type": "string"
                },
                "trigger": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "api.TaskItem": {
            "type": "object",
            "properties": {
                "finished_at": {
                    "type": "string"
                },
                "queued_at": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "task_id": {
                    "type": "string"
                },
                "trigger": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "api.TaskLogItem": {
            "type": "object",
            "properties": {
                "level": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "api.TaskLogResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.TaskLogItem"
                    }
                }
            }
        },
        "api.TaskPagination": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "api.batchRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "refreshed": {
                    "type": "boolean"
                }
            }
        },
        "api.reportRequest": {
            "type": "object",
            "required": [
                "batch_id",
                "format"
            ],
            "properties": {
                "batch_id": {
                    "type": "integer"
                },
                "file_path": {
                    "type": "string"
                },
                "format": {
                    "type": "string"
                },
                "template_id": {
                    "type": "integer"
                }
            }
        },
        "api.templateRequest": {
            "type": "object",
            "required": [
                "name",
                "task_type"
            ],
            "properties": {
                "config": {
                    "type": "object",
                    "additionalProperties": true
                },
                "name": {
                    "type": "string"
                },
                "task_type": {
                    "type": "string"
                }
            }
        },
        "models.ArbitrageOpportunity": {
            "type": "object",
            "properties": {
                "batch_id": {
                    "type": "integer"
                },
                "buy_platform": {
                    "type": "string"
                },
                "buy_price": {
                    "type": "number"
                },
                "details": {
                    "type": "object"
                },
                "id": {
                    "type": "integer"
                },
                "profit_usdt": {
                    "type": "number"
                },
                "sell_platform": {
                    "type": "string"
                },
                "sell_price": {
                    "type": "number"
                }
            }
        },
        "models.Batch": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lastRefreshedAt": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "models.ParamTemplate": {
            "type": "object",
            "properties": {
                "configJSON": {
                    "type": "object"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "taskType": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "models.Report": {
            "type": "object",
            "properties": {
                "batchID": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "filePath": {
                    "type": "string"
                },
                "format": {
                    "type": "string"
                },
                "generatedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "templateID": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
